/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saleapp;

import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;

import java.awt.Color;
import java.awt.Point;
import java.awt.TextField;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
/**
 *
 * @author nQuynhtrang
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    
    JPanel[] panels= new JPanel[2];
    
    public Login_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // set panels
        panels[0]= jPanel_TabLogin;
        jPanel_TabSignup.setVisible(false);
        panels[1]= jPanel_TabSignup;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void showPanels(JPanel panel){
        for(JPanel pnl: panels){
            pnl.setVisible(false);
        }
        panel.setVisible(true);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AllScreen1 = new javax.swing.JPanel();
        jPanel_Image = new javax.swing.JPanel();
        jLabel_Tbooks = new javax.swing.JLabel();
        jLabel_Ttree_of = new javax.swing.JLabel();
        jLabel_Ibook = new javax.swing.JLabel();
        jLabel_Ibackground = new javax.swing.JLabel();
        jPanel_TabLogin = new javax.swing.JPanel();
        jTextField_User = new javax.swing.JTextField();
        jPasswordField_Pass = new javax.swing.JPasswordField();
        jLabel_Bsignin = new javax.swing.JLabel();
        jLabel_Iuser = new javax.swing.JLabel();
        jLabel_Ilock = new javax.swing.JLabel();
        jLabel_Tcreateaccount = new javax.swing.JLabel();
        jLabel_Tsigninorsignup = new javax.swing.JLabel();
        jPanel_TabSignup = new javax.swing.JPanel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_passSign = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_tittleCreateAccount = new javax.swing.JLabel();
        jTextField_addname = new javax.swing.JTextField();
        jTextField_mail = new javax.swing.JTextField();
        jPasswordField_addPass = new javax.swing.JPasswordField();
        jLabel_bsignup = new javax.swing.JLabel();
        jLabel_Tsignin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_AllScreen1.setLayout(null);

        jPanel_Image.setLayout(null);

        jLabel_Tbooks.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_Tbooks.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tbooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tbooks.setText("BOOKS");
        jPanel_Image.add(jLabel_Tbooks);
        jLabel_Tbooks.setBounds(110, 70, 80, 30);

        jLabel_Ttree_of.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel_Ttree_of.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Ttree_of.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Ttree_of.setText("The tree of Knokledge");
        jPanel_Image.add(jLabel_Ttree_of);
        jLabel_Ttree_of.setBounds(80, 120, 140, 16);

        jLabel_Ibook.setIcon(new javax.swing.ImageIcon("D:\\2021\\ProJApp\\SaleApp\\src\\Pictures\\book.png")); // NOI18N
        jPanel_Image.add(jLabel_Ibook);
        jLabel_Ibook.setBounds(60, 150, 170, 200);

        jLabel_Ibackground.setBackground(new java.awt.Color(88, 200, 197));
        jLabel_Ibackground.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel_Ibackground.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Ibackground.setOpaque(true);
        jPanel_Image.add(jLabel_Ibackground);
        jLabel_Ibackground.setBounds(0, 0, 320, 380);

        jPanel_AllScreen1.add(jPanel_Image);
        jPanel_Image.setBounds(0, 0, 320, 370);

        jPanel_TabLogin.setBackground(new java.awt.Color(35, 47, 67));
        jPanel_TabLogin.setForeground(new java.awt.Color(255, 255, 255));

        jTextField_User.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_User.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_User.setText("Username");
        jTextField_User.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jTextField_User.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextField_User.setOpaque(false);
        jTextField_User.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UserFocusLost(evt);
            }
        });

        jPasswordField_Pass.setBackground(new java.awt.Color(36, 47, 65));
        jPasswordField_Pass.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Pass.setText("Password");
        jPasswordField_Pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPasswordField_Pass.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jPasswordField_Pass.setOpaque(false);
        jPasswordField_Pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusLost(evt);
            }
        });
        jPasswordField_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PassActionPerformed(evt);
            }
        });

        jLabel_Bsignin.setBackground(new java.awt.Color(88, 200, 197));
        jLabel_Bsignin.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel_Bsignin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Bsignin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Bsignin.setText("Sign In");
        jLabel_Bsignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Bsignin.setOpaque(true);
        jLabel_Bsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BsigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_BsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_BsigninMouseExited(evt);
            }
        });

        jLabel_Iuser.setIcon(new javax.swing.ImageIcon("D:\\2021\\ProJApp\\SaleApp\\src\\Images\\user.png")); // NOI18N

        jLabel_Ilock.setIcon(new javax.swing.ImageIcon("D:\\2021\\ProJApp\\SaleApp\\src\\Images\\lock.png")); // NOI18N

        jLabel_Tcreateaccount.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel_Tcreateaccount.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_Tcreateaccount.setText("Create Account ");
        jLabel_Tcreateaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Tcreateaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TcreateaccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_TcreateaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_TcreateaccountMouseExited(evt);
            }
        });

        jLabel_Tsigninorsignup.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_Tsigninorsignup.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_Tsigninorsignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tsigninorsignup.setText("Sign in or Sign Up");

        javax.swing.GroupLayout jPanel_TabLoginLayout = new javax.swing.GroupLayout(jPanel_TabLogin);
        jPanel_TabLogin.setLayout(jPanel_TabLoginLayout);
        jPanel_TabLoginLayout.setHorizontalGroup(
            jPanel_TabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TabLoginLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_TabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TabLoginLayout.createSequentialGroup()
                        .addComponent(jLabel_Ilock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_TabLoginLayout.createSequentialGroup()
                        .addComponent(jLabel_Iuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_TabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_TabLoginLayout.createSequentialGroup()
                                .addComponent(jLabel_Bsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel_Tcreateaccount)
                                .addGap(14, 14, 14))
                            .addComponent(jPasswordField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))))
            .addGroup(jPanel_TabLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel_Tsigninorsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TabLoginLayout.setVerticalGroup(
            jPanel_TabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TabLoginLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel_Tsigninorsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_TabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TabLoginLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_TabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Iuser, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jTextField_User))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel_TabLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Ilock, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jPasswordField_Pass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel_Bsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TabLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Tcreateaccount)
                        .addGap(58, 58, 58))))
        );

        jPanel_AllScreen1.add(jPanel_TabLogin);
        jPanel_TabLogin.setBounds(320, 0, 360, 370);

        jPanel_TabSignup.setBackground(new java.awt.Color(35, 47, 67));
        jPanel_TabSignup.setLayout(null);

        jLabel_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_name.setText("User Name");
        jPanel_TabSignup.add(jLabel_name);
        jLabel_name.setBounds(70, 80, 91, 19);

        jLabel_passSign.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_passSign.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_passSign.setText("Password");
        jPanel_TabSignup.add(jLabel_passSign);
        jLabel_passSign.setBounds(70, 200, 70, 30);

        jLabel_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_email.setText("Email");
        jPanel_TabSignup.add(jLabel_email);
        jLabel_email.setBounds(70, 140, 80, 26);

        jLabel_tittleCreateAccount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_tittleCreateAccount.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_tittleCreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tittleCreateAccount.setText("CREATE ACCOUNT");
        jPanel_TabSignup.add(jLabel_tittleCreateAccount);
        jLabel_tittleCreateAccount.setBounds(100, 0, 188, 60);

        jTextField_addname.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_addname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTextField_addname.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_addname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jTextField_addname.setOpaque(false);
        jTextField_addname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_addnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_addnameFocusLost(evt);
            }
        });
        jTextField_addname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addnameActionPerformed(evt);
            }
        });
        jPanel_TabSignup.add(jTextField_addname);
        jTextField_addname.setBounds(70, 100, 219, 29);

        jTextField_mail.setBackground(new java.awt.Color(36, 47, 65));
        jTextField_mail.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTextField_mail.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jTextField_mail.setOpaque(false);
        jTextField_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_mailFocusLost(evt);
            }
        });
        jPanel_TabSignup.add(jTextField_mail);
        jTextField_mail.setBounds(70, 160, 219, 29);

        jPasswordField_addPass.setBackground(new java.awt.Color(36, 47, 65));
        jPasswordField_addPass.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_addPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPasswordField_addPass.setOpaque(false);
        jPasswordField_addPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_addPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_addPassFocusLost(evt);
            }
        });
        jPasswordField_addPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_addPassActionPerformed(evt);
            }
        });
        jPanel_TabSignup.add(jPasswordField_addPass);
        jPasswordField_addPass.setBounds(70, 230, 219, 27);

        jLabel_bsignup.setBackground(new java.awt.Color(88, 200, 197));
        jLabel_bsignup.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel_bsignup.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bsignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_bsignup.setText("Sign Up");
        jLabel_bsignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_bsignup.setFocusable(false);
        jLabel_bsignup.setOpaque(true);
        jLabel_bsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_bsignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_bsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_bsignupMouseExited(evt);
            }
        });
        jPanel_TabSignup.add(jLabel_bsignup);
        jLabel_bsignup.setBounds(240, 300, 60, 30);

        jLabel_Tsignin.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel_Tsignin.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_Tsignin.setText("Sign In");
        jLabel_Tsignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Tsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TsigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_TsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_TsigninMouseExited(evt);
            }
        });
        jPanel_TabSignup.add(jLabel_Tsignin);
        jLabel_Tsignin.setBounds(160, 280, 50, 20);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Have an account? ");
        jPanel_TabSignup.add(jLabel2);
        jLabel2.setBounds(50, 280, 110, 20);

        jPanel_AllScreen1.add(jPanel_TabSignup);
        jPanel_TabSignup.setBounds(320, 0, 360, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AllScreen1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AllScreen1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_addnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addnameActionPerformed
        
    }//GEN-LAST:event_jTextField_addnameActionPerformed

    private void jPasswordField_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PassActionPerformed

    private void jTextField_addnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addnameFocusGained
        // TODO add your handling code here:
        if(jTextField_addname.getText().trim().toLowerCase().equals("username")){
            jTextField_addname.setText("");
            jTextField_addname.setForeground(Color.white);
        }
    }//GEN-LAST:event_jTextField_addnameFocusGained

    private void jTextField_addnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addnameFocusLost
        // TODO add your handling code here:
        if(jTextField_addname.getText().trim().equals("")||
            jTextField_addname.getText().trim().toLowerCase().equals("username")){
            jTextField_addname.setText("username");
            jTextField_addname.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_jTextField_addnameFocusLost

    private void jTextField_mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_mailFocusGained
        // TODO add your handling code here:
        if(jTextField_mail.getText().trim().toLowerCase().equals("email")){
            jTextField_mail.setText("");
            jTextField_mail.setForeground(Color.white);
        }
    }//GEN-LAST:event_jTextField_mailFocusGained

    private void jTextField_mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_mailFocusLost
        // TODO add your handling code here:
        if(jTextField_mail.getText().trim().equals("")||
            jTextField_mail.getText().trim().toLowerCase().equals("email")){
            jTextField_mail.setText("email");
            jTextField_mail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextField_mailFocusLost

    private void jPasswordField_addPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_addPassFocusGained
        // TODO add your handling code here:
        String pass= String.valueOf(jPasswordField_addPass.getPassword());
        if(pass.trim().toLowerCase().equals("password")){
            jPasswordField_addPass.setText("");
            jPasswordField_addPass.setForeground(Color.white);
        }
    }//GEN-LAST:event_jPasswordField_addPassFocusGained

    private void jPasswordField_addPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_addPassFocusLost
        // TODO add your handling code here:
        String pass= String.valueOf(jPasswordField_addPass.getPassword());
        if(pass.trim().equals("")||
            pass.trim().toLowerCase().equals("password")){
            jPasswordField_addPass.setText("password");
            jPasswordField_addPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordField_addPassFocusLost

    private void jTextField_UserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UserFocusGained
        // TODO add your handling code here:
        if(jTextField_User.getText().trim().toLowerCase().equals("username")){
            jTextField_User.setText("");
            jTextField_User.setForeground(Color.white);
        }
    }//GEN-LAST:event_jTextField_UserFocusGained

    private void jTextField_UserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UserFocusLost
        // TODO add your handling code here:
        if(jTextField_User.getText().trim().equals("")||
            jTextField_User.getText().trim().toLowerCase().equals("username")){
            jTextField_User.setText("username");
            jTextField_User.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextField_UserFocusLost

    private void jPasswordField_PassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusGained
        // TODO add your handling code here:
        String pass= String.valueOf(jPasswordField_Pass.getPassword());
        if(pass.trim().toLowerCase().equals("password")){
            jPasswordField_Pass.setText("");
            jPasswordField_Pass.setForeground(Color.white);
        }
    }//GEN-LAST:event_jPasswordField_PassFocusGained

    private void jPasswordField_PassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusLost
        // TODO add your handling code here:
        String pass= String.valueOf(jPasswordField_Pass.getPassword());
        if(pass.trim().equals("")||
            pass.trim().toLowerCase().equals("password")){
            jPasswordField_Pass.setText("password");
            jPasswordField_Pass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordField_PassFocusLost

    private void jPasswordField_addPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_addPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_addPassActionPerformed

    private void jLabel_BsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BsigninMouseClicked
        UserDAO userDAO = new UserDAO();
        String username = jTextField_User.getText();
        String password = jPasswordField_Pass.getText();
        UserModel usermodel = userDAO.selectUser(username);
        if(username.equals("")){
            JOptionPane.showMessageDialog(this, "Enter username");
            return;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Enter password");
            return;
        }
        if(usermodel == null){
            JOptionPane.showMessageDialog(this,"Account not exist");
            return;
        }
        if(usermodel.getPassword().equals(password)){
            Dashboard_Form dashboard = new Dashboard_Form();
            dashboard.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Account not exist");
            return;
        }
    }//GEN-LAST:event_jLabel_BsigninMouseClicked

    private void jLabel_TcreateaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TcreateaccountMouseEntered
        jLabel_Tcreateaccount.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_TcreateaccountMouseEntered

    private void jLabel_TcreateaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TcreateaccountMouseClicked
        // TODO add your handling code here:
        
        showPanels(jPanel_TabSignup);
    }//GEN-LAST:event_jLabel_TcreateaccountMouseClicked

    private void jLabel_TcreateaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TcreateaccountMouseExited
        jLabel_Tcreateaccount.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_TcreateaccountMouseExited

    private void jLabel_bsignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bsignupMouseClicked
        // TODO add your handling code here:
         try {
        UserDAO userDAO = new UserDAO();
        String username = jTextField_addname.getText();
        String password = jPasswordField_addPass.getText();
        String email = jTextField_mail.getText();
        if(username.equals("")){
            JOptionPane.showMessageDialog(this, "Lack of username");
            return;
        }
        
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Lack of password");
            return;
        }
        if(email.equals("")){
            JOptionPane.showMessageDialog(this, "Lack of mail");
            return;
        }
        if(userDAO.selectUser(username)!=null ){
            JOptionPane.showMessageDialog(this,"This account existed");
            return;
        }
        UserModel userModel= new UserModel(userDAO.selectAllUsers().size()+1,username,password,email);
        userDAO.insertUser(userModel);
        JOptionPane.showMessageDialog(this,"Succeed");  
             showPanels(jPanel_TabLogin);
        } catch (SQLException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_bsignupMouseClicked

    private void jLabel_BsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BsigninMouseEntered
        jLabel_Bsignin.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_BsigninMouseEntered

    private void jLabel_TsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TsigninMouseClicked
        showPanels(jPanel_TabLogin);
    }//GEN-LAST:event_jLabel_TsigninMouseClicked

    private void jLabel_TsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TsigninMouseEntered
        jLabel_Tsignin.setForeground(Color.white);
        
    }//GEN-LAST:event_jLabel_TsigninMouseEntered

    private void jLabel_TsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TsigninMouseExited
        // TODO add your handling code here:
        jLabel_Tsignin.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_TsigninMouseExited

    private void jLabel_bsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bsignupMouseEntered
        // TODO add your handling code here:
        jLabel_bsignup.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_bsignupMouseEntered

    private void jLabel_bsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bsignupMouseExited
        jLabel_bsignup.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel_bsignupMouseExited

    private void jLabel_BsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BsigninMouseExited
        jLabel_Bsignin.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_BsigninMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Bsignin;
    private javax.swing.JLabel jLabel_Ibackground;
    private javax.swing.JLabel jLabel_Ibook;
    private javax.swing.JLabel jLabel_Ilock;
    private javax.swing.JLabel jLabel_Iuser;
    private javax.swing.JLabel jLabel_Tbooks;
    private javax.swing.JLabel jLabel_Tcreateaccount;
    private javax.swing.JLabel jLabel_Tsignin;
    private javax.swing.JLabel jLabel_Tsigninorsignup;
    private javax.swing.JLabel jLabel_Ttree_of;
    private javax.swing.JLabel jLabel_bsignup;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_passSign;
    private javax.swing.JLabel jLabel_tittleCreateAccount;
    private javax.swing.JPanel jPanel_AllScreen1;
    private javax.swing.JPanel jPanel_Image;
    private javax.swing.JPanel jPanel_TabLogin;
    private javax.swing.JPanel jPanel_TabSignup;
    private javax.swing.JPasswordField jPasswordField_Pass;
    private javax.swing.JPasswordField jPasswordField_addPass;
    private javax.swing.JTextField jTextField_User;
    private javax.swing.JTextField jTextField_addname;
    private javax.swing.JTextField jTextField_mail;
    // End of variables declaration//GEN-END:variables
}
